### ISSUE TITLE
Denser Tables in Run-Detail / Comparison

### ISSUE THREAD

**Issue by I-Al-Istannen** [IPDSnelting/velcom#115]
Extracted from [this comment](https://github.com/IPDSnelting/velcom/issues/35#issuecomment-702840333):
> By the way, compared to codespeed Velcom is very generous with table spacing. A more compact layout would make it easier to visually scan the table.

Relevant image in codespeed:
![codespeed](https://user-images.githubusercontent.com/20284688/94969900-cef2ee00-0503-11eb-8765-6c7dd60c450e.png)

Reference image of a table currently in VelCom:
![Not_Dense](https://user-images.githubusercontent.com/20284688/94950300-b6bea700-04e2-11eb-8c2d-306d80b98612.png)

One possibility to solve this (`dense` tables):
![Dense](https://user-images.githubusercontent.com/20284688/94950296-b6261080-04e2-11eb-9e1b-c6a410efb5eb.png)
I am not sure whether that looks good. Without the vertical padding it is easier to get lost in the table and it looks a bit weird with all the horizontal space. I don't think we can make the table more narrow, as longer metric / benchmark names or numbers, zooming and a number of other factors could leave it looking off.

Maybe coloring the rows helps?
![image](https://user-images.githubusercontent.com/20284688/94971116-71ac6c00-0506-11eb-8fa8-952f1c25202d.png)

**Comment by Kha** [comment]
The last one definitely is a vast improvement :+1: . Any thoughts on the horizontal spacing? Should there be a maximum width (for this view only?)?

**Comment by I-Al-Istannen** [comment]
That's a bit tricky. The other two parts of that page do like some more horizontal space to display more of the commit message or to not need a second row:
![image](https://user-images.githubusercontent.com/20284688/95060180-37a3bb80-06fa-11eb-91e2-24c9301a0c7d.png)

------

Versus
![image](https://user-images.githubusercontent.com/20284688/95060232-49855e80-06fa-11eb-9f8f-401c35cf11ca.png)

------

Just resizing the results also doesn't seem ideal, but maybe it isn't *too* bad:
![image](https://user-images.githubusercontent.com/20284688/95061473-f01e2f00-06fb-11eb-851b-d11bb156aa5b.png)

-----

If we find something nice to put to the left/right or both sides of the results that could also work (or we accept the space)
![image](https://user-images.githubusercontent.com/20284688/95062092-c4e80f80-06fc-11eb-86c7-4dee26f61110.png)

-----

You probably want the whole table in the center of your vision so your eyes don't have to dart around as much (though I don't know how that scales to different screen sizes, my 15.6" laptop screen is probably not a good reference...). That would imply using a more narrow table.

Codespeed solves that issue by putting the commit detail and navigation to the right of the table. While that doesn't give much space to it, it also doesn't display anything besides the hash and date. Once TAR files can be uploaded we might not even *have* a commit to display, so I can't see a way to go the same route currently while keeping the design consistent.

Maybe you found one of those barely acceptable or have an idea to improve them. I will ask the others if they have a nicer idea as well.

**Comment by Kha** [comment]
Thanks for listing the many alternatives. The last one might not be as aesthetically pleasing as the current state, but it definitely improves readability. I like it.

**Comment by Kha** [comment]
We can also shorten "Standard Deviation" to "stddev" :)
