### ISSUE TITLE
Significance value

### ISSUE THREAD

**Issue by Kha** [IPDSnelting/velcom#129]
![image](https://user-images.githubusercontent.com/109126/95454566-ecddaa00-096c-11eb-8c6d-12bf11fb07f2.png)
Not sure if this was meant just for internal debugging, but I like it except for two issues:
* It should print not the stddev but the absolute difference divided by the stddev so that suffixing it with σ actually makes sense
* Those are wayyy too many digits. It should be, like, 2 or 3.

**Comment by I-Al-Istannen** [comment]
That was meant as a feature, but that number format slipped through.

It displays the stddev of the metric in question so you could see how much it varied, but relating that to the change sounds nicer.
