### ISSUE TITLE
Bisecting 1-up

### ISSUE THREAD

**Issue by Kha** [IPDSnelting/velcom#15]
While we're still busy setting everything up, here's a "fun" but very optional idea: for setting up projects with long histories, retroactively benchmarking all commits might not be feasible. Instead, one could benchmark the two endpoints of a range of commits, then bisect that range until all *significant* commits have been benchmarked. Given reasonable significance settings, that should hopefully be a much smaller number of commits.

I can imagine that this is slightly harder to implement than the current 1-up button since there is now a feedback loop between evaluating benchmark results and queuing new commits. It might even make more sense to implement this as a simple CLI script than to extend the frontend and backend since it will not be needed very frequently. Anyway, as said this is not a must-have feature, but I thought you might see a simple way to implement something like that.

**Comment by Kha** [comment]
Ah, this will of course not find *all* significant commits if the significant change is counterbalanced by other changes within the range, but I'm okay with that.

**Comment by Garmelon** [comment]
This seems like a good use case for a separate script interacting with the API, but it will take a while until we'll get to implementing something like this.

**Comment by Kha** [comment]
Not that important to us anymore
