### ISSUE TITLE
Comitter date

### ISSUE THREAD

**Issue by Kha** [IPDSnelting/velcom#151]
I don't quite remember if we've talked about this before, but connecting commits in the graph ordered by author date (i.e. in the zoomed-out view) is highly misleading since that might not be the actual commit order. The committer date is accurate for comparison and while it can lead to commits being bunched up at the same x position, I suppose the "day-equidistant" option (typoed as "equistant" btw) should help with that. For Lean I would like to have at least a config option to use the committer date project-wide; I don't necessarily need a UI toggle button.

**Comment by Kha** [comment]
And while in the zoomed-in view commits are connected correctly, using the author date means that there may be confusing gaps in the graph since some commits of the viewed sequence have author dates outside the view. So I would prefer committer dates there as well.

**Comment by I-Al-Istannen** [comment]
I would put a safe harbor statement here, as I quickly hacked together a small prototype, just to see what it *might* look like. There ~~could be~~ *are* bugs lurking in there and the code is rubbish, but it resulted in this:

https://i.imgur.com/sQKTbcA.mp4

It first sorts all commits topologically using an inefficient DFS and then sorts it by committer date (taking advantage of the java sort being stable) to ensure the rebased commits appear in the correct order.

Do you think that's workable or are you now horrified that sorting by committer date won't work? I sadly don't have up-to-date lean data to test it with.

**Comment by I-Al-Istannen** [comment]
> And while in the zoomed-in view commits are connected correctly, using the author date means that there may be confusing gaps in the graph since some commits of the viewed sequence may have author dates outside the view. So I would prefer committer dates there as well.

The PR doesn't completely fix this, as merge commits can still be arbitrary far apart from their parents. But as Lean is rebase-based, that shouldn't be a problem.

Day-Equidistant mode is likely a requisite when peeking at the commits around rebase points. ECharts will show *all* values in the tooltip, but it isn't really helpful to see a vertical line of commits. Adding the Day-Equidistant mode to the faster Dytail graph would be nice, but isn't done yet. At the resolution the Dytail graph operates at, that might not be as important hopefully.
