### ISSUE TITLE
New commits should be pushed to the end of the queue

### ISSUE THREAD

**Issue by Kha** [IPDSnelting/velcom#158]
Otherwise the order of "Recent (significant) runs" on the Home tab is essentially arbitrary. That is, unless commits are re-run, Home should preserve the commit order.
![image](https://user-images.githubusercontent.com/109126/97544546-0f8e3c00-19ca-11eb-9c02-4882335c1fff.png)

**Comment by I-Al-Istannen** [comment]
Hm. The current queue order was deliberately chosen, as new commits are probably more interesting than older ones. So if you have too many and your runners can't keep up with every single one, getting an up-to-date snapshot is likely more valuable.

I think the version currently in stable uses some kind of topological sorting. The new listener branch merged in main isn't quite sure what it wants to use yet.

**Comment by Kha** [comment]
> The current queue order was deliberately chosen, as new commits are probably more interesting than older ones. So if you have too many and your runners can't keep up with every single one, getting an up-to-date snapshot is likely more valuable.

Ah, I suspected something like this. This is not an issue for Lean (yet?), but I also improved the benchmarks so that changes are more likely to be discovered at the actual commit responsible for them, so the commit order might not be as important anymore. Let's wait and see.
