### ISSUE TITLE
Updating repo name makes velcom forget all repos

### ISSUE THREAD

**Issue by Garmelon** [IPDSnelting/velcom#176]
When updating the name of a repo in the repo detail view, velcom seems to forget which repos exist. This can be seen when trying to switch to a different repo immediately after renaming the repo: 
![image](https://user-images.githubusercontent.com/11077553/100008585-8bab5200-2dc5-11eb-9838-667a00a22a4e.png)

**Comment by I-Al-Istannen** [comment]
It actually doesn't, it just does update the name in the text field for you. And as the text acts as a filter, no repo with that name can be found afterwards. Just deleting the text is enough. The same can also be achieved by clicking into it and then letting go - this will re-accept the current entry and update the text to its new value.

The correct repo is updated, so this looks like a quirk in the `v-autocomponent` method. I currently doubt it is worth the effort to dig deeper into how vuetify handles that there and manually invalidate it, as it fixes itself if you refresh, navigate away, click into the field or delete its contents.
