### ISSUE TITLE
Show log while building

### ISSUE THREAD

**Issue by Kha** [IPDSnelting/velcom#18]
When I'm too impatient, or something is taking suspiciously long, I often used to log into the screen running the old codespeed runner and take a look at the current build logs. I can imagine implementing something like that to be quite a bit more complicated with this kind of infrastructure, but it would be a pity if the more powerful system wasn't able to replicate this simple action.

**Comment by Kha** [comment]
For a start, showing just the elapsed time would already make the queue view more informative.

**Comment by Garmelon** [comment]
Would showing the last ~100 or so lines work, or do you want to see the entire output?

**Comment by Garmelon** [comment]
Regarding the current logs: The bench script could redirect the stdout of the programs it calls to stderr. Then the runner could print all stderr it receives from the benchscript. This solution feels a bit ugly to me, but on the other hand, the bench script's stdout is reserved for the bench results.

**Comment by Kha** [comment]
> The bench script could redirect the stdout of the programs it calls to stderr.

As you said, it *must* in fact do that to prevent messing up the bench results

**Comment by I-Al-Istannen** [comment]
We will have a look ourselves to address the problems, but if you want you can quickly note down what you think or want out of this feature [here](https://github.com/IPDSnelting/velcom/pull/121#issuecomment-713500161).
