### ISSUE TITLE
Runner hangs on too much stderr output

### ISSUE THREAD

**Issue by Kha** [IPDSnelting/velcom#20]
This is because you block on reading stdout before ever reading stderr: https://github.com/IPDSnelting/velcom/blob/68ca5a3be2cce80d23128542eb2460f56167a66e/backend/shared/src/main/java/de/aaaaaaah/velcom/runner/shared/ProgramExecutor.java#L60-L71
I believe you will need two separate threads for this.

**Comment by I-Al-Istannen** [comment]
This should probably be fixed in the current development version [here](https://github.com/IPDSnelting/velcom/blob/runner-protocol/backend/shared/src/main/java/de/aaaaaaah/velcom/shared/util/execution/ProgramExecutor.java#L46-L47), though we should probably add a small unit test to verify that.

**Comment by I-Al-Istannen** [comment]
It didn't seem to hang when outputting around 30.000 lines of stderr text (displaying live output of downloading maven libraries is a neat way to test it), so I'd consider this solved.
