### ISSUE TITLE
Client and server disagree whether I'm still logged in

### ISSUE THREAD

**Issue by Kha** [IPDSnelting/velcom#207]
After some time, the backend tells me I'm not authorized on initiating privileged actions, but the frontend still shows "logout" even after refreshing the site.

**Comment by I-Al-Istannen** [comment]
Does clicking "Logout" and then logging in allow you to execute privileged operations again?

**Comment by I-Al-Istannen** [comment]
That's quite curious. The frontend says it is "logged in" if it has a repo/admin and token stored locally, it shouldn't really be able to expire though evidently it does...

I will try to reproduce that myself, but if you stumble upon it again and have the time and motivation it would be interesting wether there is an `Authorization` header sent with the requests.

**Comment by Kha** [comment]
Ah, it might actually be that that particular session was still open from before I changed the token, not sure... I'll keep an eye open

**Comment by Kha** [comment]
I guess it really was my own fault
