### ISSUE TITLE
Build log vanishes after successful completion

### ISSUE THREAD

**Issue by Kha** [IPDSnelting/velcom#212]
It would be nice to keep the log on screen even if benchmarking succeeded.

**Comment by I-Al-Istannen** [comment]
Is it important that it displays the last lines *the program produced*? If the frontend just keeps the last received data it might not include the last lines, as the lines are only updated periodically in the backend currently.

**Comment by Kha** [comment]
Oh I see now how it might be weird to stop at a partially finished log. Would it be hard to include a final log push after completion?

**Comment by I-Al-Istannen** [comment]
Probably not as we store the full log of finished runs anyways, but I will have a closer look when I implement it. Just wanted to know whether that's something worth implementing :)

**Comment by Kha** [comment]
Well, if you give me a button to that log on the run-detail page, that would be sufficient as well :) . I assumed only logs of failed runs were stored.

**Comment by I-Al-Istannen** [comment]
And you are right, I was just about to edit that part of the message. I will need to have a look at a few runner details, there are a few places which sound suitable but I will refrain from commenting before I made sure it works ;)
