### ISSUE TITLE
Optimize UI for single-repo instances

### ISSUE THREAD

**Issue by Kha** [IPDSnelting/velcom#23]
As long as there is only a single configured repository, I should never need to select it, or even see any selection widget. I'm OK with the repo being part of permalinks since I can see that later adding more repos would break them otherwise.

**Comment by Kha** [comment]
Depending on what we do with the two graphs, we might also hide the repo comparison tab entirely in that case.

**Comment by oudemia** [comment]
Considering that the detail graph will also use time for navigation when using the new API, I agree that it would be redundant to show both graphs... The detail graph should provide all information for a single repo after all.
