### ISSUE TITLE
Expand/collapse section by clicking anywhere on the header

### ISSUE THREAD

**Issue by Kha** [IPDSnelting/velcom#231]
E.g. I tried to expand "Search and Compare" by clicking on the text

**Comment by I-Al-Istannen** [comment]
That sounds useful, but that widget died in the current version. It was replaced by the run search (e.g. [here](http://speedcenter.informatik.kit.edu/velcom/prepare-run-compare/b6c58de3-5376-4c71-a740-2b8a7a5ac7c2)) which asks the backend for help and can therefore actually search across *all* known runs.

I hope that was what you used "Search and Compare" for?

**Comment by Kha** [comment]
*presses Ctrl+F5* Ah, looks great! I was able to find my commit, though what I actually wanted to do is to look at a *single* commit, which the UI doesn't immediately make available.

**Comment by I-Al-Istannen** [comment]
That's an interesting point. Were you looking for a *run* (i.e. a tar or a commit that was measured) or a *commit* (with or without a run)?

**Comment by Kha** [comment]
You shouldn't expect end users to know the difference between the two :) ... but yes, I was looking for a run given the commit message, or at least I was hoping it had a run. I found it via the graph instead.

**Comment by I-Al-Istannen** [comment]
Currently only runs can be searched, as you can't compare commits without one. Having lots of irrelevant results in the compare field search didn't feel right.

Searching a single commit/tar is probably orthogonal? You don't necessarily want to compare it with anything (else you'd use the compare page) but you might want to see its detail page. If you change your mind then, you can always compare it from there.

**Comment by Kha** [comment]
Yes, now that it's not called "Search & Compare" anymore, there could be a separate "Search Run" functionality
