### ISSUE TITLE
Home: combination of incremental loading and paging doesn't make sense

### ISSUE THREAD

**Issue by Kha** [IPDSnelting/velcom#247]
I think paging is used everywhere else, so scrap the "Load more..." button?

**Comment by Kha** [comment]
On the other hand, incremental loading feels quite natural for a "homepage". It just stops feeling natural when the button stops working because the paging table showed up.

**Comment by I-Al-Istannen** [comment]
I will change that to an infinite list with a "load more" button then. If you load a few thousand entries it will probably slow down your browser but that isn't a likely scenario.
The scrolling will also be a bit more annoying, but if you explicitly loaded them you are probably fine with that.
