### ISSUE TITLE
No way to initiate comparison from a tar run result page

### ISSUE THREAD

**Issue by Kha** [IPDSnelting/velcom#254]
See e.g. http://speedcenter.informatik.kit.edu/velcom/run-detail/cb0ccafc-b921-436b-a961-4ae110bd0ebe

**Comment by I-Al-Istannen** [comment]
Ooof. That hurts. You can still compare it by going to http://speedcenter.informatik.kit.edu/velcom/search/cb0ccafc-b921-436b-a961-4ae110bd0ebe, but that should *definitely* be fixed.

**Comment by Kha** [comment]
Yeah, I initiated it from the base commit instead as a workaround

**Comment by I-Al-Istannen** [comment]
Voogle also finds it in the search page (http://speedcenter.informatik.kit.edu/velcom/search) so that might be the most convenient workaround:
![grafik](https://user-images.githubusercontent.com/20284688/115877703-07c6c600-a448-11eb-9fc2-66d5dfd66e45.png)

**Comment by Kha** [comment]
I see. There is no direct link to the search page, is there?

**Comment by I-Al-Istannen** [comment]
There actually is one here:
![grafik](https://user-images.githubusercontent.com/20284688/115918086-5a6ba680-a477-11eb-917f-c22546566a94.png)

I will take the hint that *nobody* will ever find that button though, but we weren't quite sure where to place it. It *could* get its own navigation bar button, but that might be getting a bit crowded up there.

Did you have any place in mind where you would have expected it?

As the search page has backend support it *should* do what you'd expect in most cases and find any commit/run by message, author, run id or commit hash. I also seem to have removed using a branch as a comparison target (so you can compare with e.g. `master`) when redesigning the page, so I'll add that to my todo list.

**Comment by Kha** [comment]
I can't really think of a use case where I would search for a specific commit in VelCom, so I'm content if the initial issue is fixed. Even better with branches as comparison targets.

**Comment by I-Al-Istannen** [comment]
### Tar compare button
The tar page now has a comparison Button:
![grafik](https://user-images.githubusercontent.com/20284688/115956042-ec68c300-a4fa-11eb-8a64-f19cc2a4a92d.png)

### Comparing with branches
And you can compare things with branches (though you might need to wait a few hundred milliseconds as VelCom needs to request the current branch head on-demand). In my tests the delay was around 20-80 ms until the correct commit message appeared.

It will start like this (loading message and compare icon on the right grayed out)
![grafik](https://user-images.githubusercontent.com/20284688/115956103-3a7dc680-a4fb-11eb-8e83-32c730a145e1.png)


And end here (Commit message in subtitle, as a run exists you can select it on the right now):
![grafik](https://user-images.githubusercontent.com/20284688/115956075-15895380-a4fb-11eb-82be-785b31fe02fa.png)

Feel free to complain if you want more data or something else somewhere :)

**Comment by Kha** [comment]
Awesome! :tada:
