### ISSUE TITLE
Comparisons should show both absolute and relative differences

### ISSUE THREAD

**Issue by Kha** [IPDSnelting/velcom#255]
A percentual change column would be very helpful in cases like
![image](https://user-images.githubusercontent.com/109126/115876341-7a36a680-a446-11eb-967f-086f299ab2e1.png)

**Comment by I-Al-Istannen** [comment]
A random thought: Would a bar chart or similar graph be useful to visualize changes? I am not sure how well it scales to lean's massive set of measurements, but it might make such comparisons more intuitive?

**Comment by Kha** [comment]
Hmm, not sure how that would help on a <1% change like above.

**Comment by I-Al-Istannen** [comment]
A horizontal bar chart would have a few hundred to thousand pixels and could potentially do show that. In any case it might allow for a better overview than reading 60 lines in a table and trying to find out which changed and if there are any outliers.

The detail graph is providing an overview for a few dimensions *over time*, the chart here would be an overview over *all* dimensions for a single comparison. A more visual version of the significance chips basically.

I am not sure if that is truly useful, it was just a random idea while scrolling through the dimensions in the comparison page.
