### ISSUE TITLE
Rearranging the repo detail page

### ISSUE THREAD

**Issue by I-Al-Istannen** [IPDSnelting/velcom#258]
### About this issue
In the name of consistency and after noticing, that the new repo comparison layout feels a bit more usable, I wanted to rearrange the detail page.

However, I absolutely *do not* want to just change things around for its own sake, so it would be helpful if @kha could comment on how he uses it and whether the changes make it easier or more annoying to use. The goal was to reduce the amount of scrolling needed to adjust the graph to your liking.

Whitespace, padding, exact alignments and behavior on smaller devices are still up in the air.

The main problems I am currently unsure about are:
1. Do we really want to give up that horizontal space?
2. The matrix selector wants a lot more horizontal space than the location on the left can afford. We could move it down if it gets too large but then you don't really gain much - you still need to scroll around quite a bit when changing what you are displaying.  
The last video might address that issue well enough though? You can see how what you are doing effects the graph through the semi-transparent dialog background and escape the dialog by hitting ESC or clicking the close button.

#### New Repo Comparison
![grafik](https://user-images.githubusercontent.com/20284688/116460309-36d5a100-a867-11eb-831c-3f088c88ea4c.png)

----

#### Old Repo Detail
![grafik](https://user-images.githubusercontent.com/20284688/116460874-d7c45c00-a867-11eb-809b-5c37c036f3b7.png)

----

#### Proposed Repo Detail *draft*
![grafik](https://user-images.githubusercontent.com/20284688/116460521-6e444d80-a867-11eb-90b0-09f383574bb7.png)

#### Dealing with wide selectors
https://user-images.githubusercontent.com/20284688/116594346-639abe80-a922-11eb-969c-b9d6a15032da.mp4

**Comment by Kha** [comment]
Looks great to me!
