### ISSUE TITLE
Graph tooltip hides current position

### ISSUE THREAD

**Issue by Kha** [IPDSnelting/velcom#263]
![image](https://user-images.githubusercontent.com/109126/119166064-7a828b80-ba5e-11eb-988d-e4a9f120a4ee.png)

This is likely fallout from #259

**Comment by I-Al-Istannen** [comment]
Yea, that looks like there isn't enough horizontal space to completely move it out of the way. Currently the tooltip is set to "confined", so it will stay inside the graph view, preventing it from assuming any useful position in your example.

We could try to lift that confinement and find a useful position ourselves. I will have a look at that.
