### ISSUE TITLE
Significance in comparison page

### ISSUE THREAD

**Issue by Kha** [IPDSnelting/velcom#272]
The comparison page should show as much information for judging significance as the standard run page, i.e. "significant results" chips and, say, at least stddev% (of the second run should be sufficient).

**Comment by I-Al-Istannen** [comment]
What are you actually looking for when visiting that page? What are you interested in? Based on the comments it looked like you skimmed for a statistically significant difference (based on the stddev)?

I'll have a look at adding a stddev% column and when the GitHub bot learns what's significant the comparison page can follow suit.

----

I got lost in the 75-entry Lean table and was just randomly exploring a way to visualize that a bit better during the late hours of the night.
A bar chart sounded like it could be somewhat semantically fitting, as you do are comparing the magnitude of different items.

Just for fun I threw [this run](http://speedcenter.informatik.kit.edu/velcom/run-detail/bab50d33-13a1-40c4-85a0-fda5f93f8b22/4ed66cae3e47dd186a47c83e237ace6bf559e2a6)
![grafik](https://user-images.githubusercontent.com/20284688/121823158-9c5ce000-cca3-11eb-84fc-ca49ba71227b.png)

into a bar chart displaying `(new value - old value) / stddev of new values` which yielded this (with a few dimensions marked as insignificant removed):
![grafik](https://user-images.githubusercontent.com/20284688/121823204-f52c7880-cca3-11eb-9ed5-630beabe9f9d.png)
(compilation, initialization, import, task-clock, parsing, wall-clock)

In all likelihood it is completely and utterly useless but as I already hacked a small prototype together I felt throwing it out in the void was at least not actively harmful. I probably spent too much time on the overview bar graph and it is starting to get to me...

**Comment by Kha** [comment]
The significance chips are usually all I need to know. They're great! So showing them wherever sensible (GitHub comment, comparison page) would be perfect.
I don't really care how many sigmas a change is as long as it's "sufficiently many" so I'm not sure that graph would help me :) .

**Comment by I-Al-Istannen** [comment]
Understandable :)

This is what it looks like now, I hope that's closer to what you'd expect.

![grafik](https://user-images.githubusercontent.com/20284688/122126331-e07deb00-ce31-11eb-8c5f-8399726947f9.png)


----

![grafik](https://user-images.githubusercontent.com/20284688/122126030-75341900-ce31-11eb-9a98-a9230264e2c9.png)

**Comment by Kha** [comment]
Looks great! Where do the gray chips come from though?

**Comment by Kha** [comment]
Oh I see, I guess it's a metric without an "is better" direction

**Comment by Garmelon** [comment]
This change has now been pushed to `stable`.
