### ISSUE TITLE
Support errors on the benchmark level

### ISSUE THREAD

**Issue by Kha** [IPDSnelting/velcom#29]
In most use cases, only full benchmarks can fail, not individual metrics of a benchmark. Additionally, some metrics are discovered dynamically while running the benchmark, so we don't even know the set of metrics when the benchmark has failed. Thus it should be possible to specify an error for a benchmark without specifying any metrics.

**Comment by I-Al-Istannen** [comment]
#141 allows empty benchmarks at least. That doesn't help you with a custom error, but it allows you to just leave an empty benchmark in the output. Runs like http://speedcenter.informatik.kit.edu/velcom/run-detail/bab50d33-13a1-40c4-85a0-fda5f93f8b22/943687ad0977f11809ae80353d67e11cc0c2a02f should succeed after this change.

**Comment by Kha** [comment]
:tada:

**Comment by I-Al-Istannen** [comment]
### Valid outputs

You can specify a benchmark with metrics. Individual metrics are allowed to fail.
```json
{
    "benchmark": {
        "metric-1": {
            "results": [ 1337 ],
            "unit": "hope",
            "resultInterpretation": "MORE_IS_BETTER"
        },
        "metric-2": {
            "error": "I am an error :("
        }
    }
}
```

You can also just specify a benchmark *without any metrics*. This could happen when you auto-discover metrics for a benchmark and that discovery didn't find any metric.
```json
{
    "benchmark": {}
}
```

Units and interpretations are *optional*. If they are not provided VelCom will use the unit/interpretation of the previous run. If it is provided it will overwrite the unit/interpretation for that metric.
```json
{
    "benchmark": {
        "metric-1": {
            "results": [ 1337 ],
        },
        "metric-2": {
            "error": "I am an error :(",
            "unit": "you can even change unit/interpretation in errors!",
            "resultInterpretation": "LESS_IS_BETTER"
        }
    }
}
```

### Invalid outputs

If you specify a metric you need to provide either an error or some results. The following is therefore invalid:
```json
{
    "benchmark": {
        "metric": {}
    }
}
```

Top-level benchmark errors are not supported. The following is therefore invalid:
```json
{
    "benchmark": {
        "error": "Error during metric discovery :/"
    }
}
```

### How you can emulate top-level errors (if it is not important that it failed)
You need to output the benchmark without any metrics (or omit it entirely). You can output whatever you want on `STDERR` but it *will be ignored* and not persisted, if the benchmark script returns successfully (exit code 0 and no syntax errors in the output).  
For all practical purposes the error output here is *lost*.
```json
# STDOUT (valid output, no top-level benchmark error given)
{
    "benchmark": {}
}
# STDERR
Error during metric discovery for benchmark 'benchmark'

# Alternative valid STDOUT (Without even mentioning the benchmark that has no metrics)
{}
```

### How you can emulate top-level errors (if it is important that it failed)
If you want to keep the error and make it visible in the UI you need to do something like this:
```json
# STDOUT
Whatever you want.

# STDERR
Error during metric discovery for benchmark 'benchmark'

# EXIT CODE
!= 0
```
Exiting with a code `!= 0` will cause the *whole run* to fail and the `STDOUT` and `STDERR` output to be shown on the run detail page.


### What you can't do currently
Fail a benchmark (and see that in the UI somewhere) while keeping the results, i.e. don't fail the *whole run* but just that *one benchmark*.
```json
{
    "benchmark": {
        "error": "Error during metric discovery :/"
    },
    "other-benchamrk": {
        "metric": {
            "results": [ 20 ],
            "unit": "I will show up and be used!"
        }
    }
}
```

**Comment by I-Al-Istannen** [comment]
I hope you aren't longing for this and are fine with the workarounds mentioned above. It is quite unlikely that this will be implemented in VelCom as of now.

If you can live without that feature, feel free to close this issue. Otherwise we can leave it open and let it serve as a reminder.

**Comment by Kha** [comment]
Yeah, that's fine with me :)
