### ISSUE TITLE
Provide truly base URL-agnostic Docker containers

### ISSUE THREAD

**Issue by sgraf812** [IPDSnelting/velcom#293]
I tried replicating the setup at speedcenter.informatik.kit.edu/velcom/ for the compilers lab and noticed that I can't easily copy the config.yml, change speedcenter.informatik.kit.edu/velcom/ to speedcenter.informatik.kit.edu/test/ and enjoy running a test instance.

It appears the frontend is compiled during build-time of the docker container, which will hardcode the base URL into the compiled assets based on a particular .env.* file, like https://github.com/IPDSnelting/velcom/blob/main/frontend/.env.production-kit.

Fortunately, there's a package on GH without the -kit prefix that seems to work under the root. Judging from the data it serves, it uses https://github.com/IPDSnelting/velcom/blob/6fe1c52a3e40b9348b327752120200a01bc19fac/frontend/.env.production or some such, which still means that the `VUE_APP_BASE_URL` is off.

I wonder if there is a way to make one docker image that compiles the frontend files as part of its startup procedure, depending on a given .env.production file. Probably there is, but that probably entails more tinkering than I'd like.

I guess I'll just compile the docker image manually in the meantime.

**Comment by I-Al-Istannen** [comment]
Yes, that is a bit of a problem. You can build a docker container that compiles the frontend at startup, but that is a bit of a bummer as it would make the startup time quite large.

The reason for the whole thing is that you can not use use an env variable or such for the frontend as the frontend is compiled down to a set of static files which can not access *anything* from their docker container - they are just html/js/css files executed by the browser.

The frontend could try to detect the path at runtime based on the location attribute but that seemed a bit fiddly the last time I pondered this issue. I could have a look at whether I can make the detection work well enough though. It might be worth the effort to have a truly one-size-fits-all container.
