### ISSUE TITLE
Control runners from web UI

### ISSUE THREAD

**Issue by Kha** [IPDSnelting/velcom#36]
Suspend/resume a runner for when the machine is temporarily needed for other purposes. Restart a runner for reloading the benchmark script.

**Comment by I-Al-Istannen** [comment]
> Restart a runner for reloading the benchmark script.

What exactly is that supposed to do? The benchmark script is in a git-controlled repository. Any changes to the script will cause the HEAD commit to change and after the polling period VelCom will pick up that change, supplying runners with the new repository.

Is this for forcing a runner to re-download the benchmark repo? I.e. it should be functionally identical to stopping the runner, deleting the benchmark repo and starting it up again?

**Comment by Kha** [comment]
> after the polling period VelCom will pick up that change, supplying runners with the new repository.

I see. There is no documentation on how to update the benchmark script, so restarting the runner is what I've done so far, which seemed to work reliably. So yes, I'd like to have a way to force runners into fetching the benchmark script repo.

**Comment by Garmelon** [comment]
With #137 clicking on the refresh button in the queue (only visible if logged in as global admin) will fetch all repos including the bench repo, and distribute the new bench repo version to runners as necessary.

**Comment by Garmelon** [comment]
As per your email, you are not interested in suspending/resuming runners any more? @Kha

**Comment by Kha** [comment]
Yeah, if you ssh into the machine anyway to do other things, I guess you can just use `systemctl` for that. Reloading the runner script was the real motivation.
