### ISSUE TITLE
Rename `master` and `develop` branches

### ISSUE THREAD

**Issue by Garmelon** [IPDSnelting/velcom#42]
I propose to rename the `master` branch to `stable` and the `develop` branch to `master`. That way, development happens on the `master` branch like most github projects, making the project easier to work with and mistakes (e. g. accidentally opening a PR on the wrong branch) less likely. Also, the name `stable` describes the function of the deployment branch better than `master`.

If this change makes sense, the CI config would have to be changed, but probably not by much.

**Comment by Kha** [comment]
Sounds good to me

**Comment by fread** [comment]
I'm done setting up `stable`. 

Also, I fixed the runner deployment, which we must have abandoned midway when we first worked on it. You probably want to include those commits in `main`.

**Comment by fread** [comment]
Update: My patches duplicate #39, which is already on `develop`. Should I revert and we merge `develop` into `master` now?

**Comment by I-Al-Istannen** [comment]
Sounds finde, but I'd give the CI a few minutes to quickly build the develop after the PR. The other Frontend PR will need to done later on, I will sort out all conflicts that might arise due to the renaming when it is ready to be merged.

**Comment by I-Al-Istannen** [comment]
Works well enough (the only small issue, delayed navigation items on first load, is not present on the speedcenter instance), so merging develop into master should be fine.

**Comment by I-Al-Istannen** [comment]
The branches should be renamed, the branch protection rules adjusted and our CI is migrated. It doesn't look like the changes were picked up in your instance, so maybe the stable deploy doesn't quite work yet or I am missing something.

In either case you can finish(?) setting up CD on the stable branch and close the issue when you are done.
If there are any problems with it, feel free to mention me :)

**Comment by Kha** [comment]
Deployment should be fixed now
