### ISSUE TITLE
Zombie processes not reaped

### ISSUE THREAD

**Issue by I-Al-Istannen** [IPDSnelting/velcom#7]
Somehow the runner sometimes leaves a few Zombie processes behind — of programs it didn't even spawn itself.  
In the screenshot below you can see a rogue `node` process *with CPU time*. Node is spawned by our `make` benchmark script.  
Maybe it tried to `SIGTERM` `make` and the signal did not properly propagate to all child processes?  

A bit more investigation is needed here, likely either after the runner protocol was adjusted or when process tree killing was implemented.

![grafik](https://user-images.githubusercontent.com/20284688/84427590-7383b400-ac25-11ea-92b2-3606cd009ab2.png)

**Comment by parttimenerd** [comment]
I had a related problem. The solution was to assign the started process a group id and to then send the terminate signal to the whole group. The spawned processes belong to the process group. See https://stackoverflow.com/a/32222971 for an example in python.

**Comment by I-Al-Istannen** [comment]
I changed that to kill the whole process tree (walk all descendants, then kill every one it can find). That *might* be enough if it includes all children, but process or cgroups are a better solution.

I did look into them, but I couldn't find any native option in java to set the sid or create a new cgroup and I couldn't find it in the bugtracker or anywhere else in my - admittedly not too exhaustive - search. Makes one a bit jealous of python :P

That means I'd likely have to resort to calling out to a small helper bash script or shell one-liner or something similar that manages these details... Doesn't sound like the most robust solution but java seems to be a bit too platform independent and/or high level to care about that for now :/ 

I will experiment a bit whether a forked and orphaned child is listed in descendants, but I would guess it just walks down the process tree, missing orphans in the process.

**Comment by I-Al-Istannen** [comment]
The issue still persist but I can't reproduce it when *not running my runner inside docker*. I am quite certain I have fallen into https://blog.phusion.nl/2015/01/20/docker-and-the-pid-1-zombie-reaping-problem/ . The runner in my screenshot was actually PID 1 (when viewed from inside the container's PID namespace). This meant any orphaned process is re-parented to it and our runner is not behaving like a proper init process and reaping the children.

When watching the htop output from inside the container, I could see a `sleep` process being moved from its proper position to a child of the runner and *sibling* of the make script that caused it to be created a few forks down. This is congruent with the theory above.

I don't think we should try to be a good init process and instead you need to either
- run the runner *outside* of docker, where a grown-up init process is around to adopt children
- use e.g. the `my_init` script from the link above to correctly reap those zombies

I will close this issue in a few days unless you object and want us to either provide a proper init script/configuration or teach the runner to reap adopted children (If Java even has the necessary low-level signal handlers needed, which I am not sure of).

That was a weird one...
